### ISSUE TITLE
Wordpress error - Call to undefined function str_contains()

### ISSUE THREAD

**Issue by stufro** [Xtendify/Simple-Calendar#382]
After upgrading to the latest version of the plugin, I receive the following error on my WordPress site: `Call to undefined function str_contains()`

When I disable the plugin the site starts working again.

**Wordpress version:** 5.7.8
**PHP version:** 7.4.33

**Comment by denis-troller** [comment]
I can confirm this. 
str_contains is a php 8 function. 
I myself am running 7.3.33

**Comment by rosinghal** [comment]
This problem has been introduced since we updated Carbon dependency to support PHP 8.2.
Possible solutions recommended at https://github.com/briannesbitt/Carbon/issues/2722 is https://github.com/humbug/php-scoper/blob/main/docs/further-reading.md#polyfills 

I have added the tag `help wanted`, any contributions will be helpful.

**Comment by rosinghal** [comment]
Can replicate the behaviour.


_`str_contains` was added as a polyfill in v[5.9.0](https://core.trac.wordpress.org/changeset/52039)._

**Comment by rosinghal** [comment]
@stufro @denis-troller @gacharijohn can you please verify if https://github.com/Xtendify/Simple-Calendar/releases/download/3.1.38-beta1/simple-calendar-3.1.38-beta1.zip works for you?

**Comment by gacharijohn** [comment]
@rosinghal it does work for me.

**Comment by stufro** [comment]
@rosinghal yes works for me too, thank you for the patch.

**Comment by rosinghal** [comment]
Updated in https://wordpress.org/plugins/google-calendar-events/.
